---
exclude_paths:
  - '**/__init__.py'
  - 'samples/**'
  - 'CODE_OF_CONDUCT.rst'
  - 'CONTRIBUTING.rst'
  - 'paper/**'
  - '**/*.sh'
  - 'doc/source/conf.py'
  - 'tasks.py'
  - '.github/**'
  - 'examples/**'
